version: "3.9"
services:
  web:
    build: ./web
    image: "drsimage:web"
    ports:
      - 80:80
      - 443:443
    links:
      - "db:db_container"
    container_name: "drs_webcontainer" 
  db:
    build: ./db
    image: "drsimage:db"
    ports:
      - 4306:3306
    expose:
      - 3306
    container_name: "drs_dbcontainer"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: